### ISSUE TITLE
Deploying on origin/centos

### ISSUE THREAD

**Issue by andrewklau** [openshift/openshift-tools#2187]
I've been looking into testing this for deploying some of the components on an origin cluster.
I have created and imported the generated secrets but the first build will fail at `Save scriptrunner's ssh key`

https://github.com/openshift/openshift-tools/blob/prod/docker/oso-zabbix-server/centos7/root/config.yml#L78
Replacing this seems to resolve it but perhaps I'm missing some config steps?

```
-        {% set rsa_key = "" %}
-        {%- set key_name = "g_user_" + g_zbx_actions_config.zbx_scriptrunner_user %}
-        {%- set rsa_key = hostvars["localhost"][key_name]["priv_key"] %}
-        {{- rsa_key -}}
+        {{- g_user_scriptrunner_priv_key -}}
```

**Comment by bdurrow** [comment]
@andrewklau, Did you ever manage to complete a deployment.  I'm looking to deploy to an origin cluster (in google cloud instead of aws as I imagine you are).

**Comment by andrewklau** [comment]
@bdurrow unfortunately not

**Comment by joelddiaz** [comment]
You're going to want to create a secret for the zabbix server container that has something that looks like this example config: https://github.com/openshift/openshift-tools/blob/prod/docker/local_development/monitoring-secrets/zabbix-server-vars.yml, and mount it into the container at /secrets . An example deploymentconfig can be seen here: https://github.com/openshift/openshift-tools/blob/prod/docker/local_development/zabbix_monitoring_cent7_local_dev.yaml#L52
