### ISSUE TITLE
Local development of openshift-tools monitoring 

### ISSUE THREAD

**Issue by cragr** [openshift/openshift-tools#2398]
I'm attempting to build a local development of the openshift-tools monitoring following the instructions here: https://github.com/openshift/openshift-tools/blob/stg/docs/local_development_monitoring.adoc

The script I am having an issue with is "start-local-dev-env.sh"  the output of that script is below"

> $ ./start-local-dev-env.sh 
> Opening ports on default zone for DNS and container traffic (non-permanent)
> success
> success
> success
> success
> -- Checking OpenShift client ... OK
> -- Checking Docker client ... OK
> -- Checking Docker version ... OK
> -- Checking for existing OpenShift container ... OK
> -- Checking for registry.access.redhat.com/openshift3/ose:v3.4.1.12 image ... 
>    Pulling image registry.access.redhat.com/openshift3/ose:v3.4.1.12
>    Pulled 1/4 layers, 25% complete
>    Pulled 2/4 layers, 50% complete
>    Pulled 3/4 layers, 75% complete
>    Pulled 4/4 layers, 100% complete
>    Extracting
>    Image pull complete
> -- Checking Docker daemon configuration ... OK
> -- Checking for available ports ... 
>    WARNING: Port 443 is already in use and may cause routing issues for applications.
> -- Checking type of volume mount ... 
>    Using nsenter mounter for OpenShift volumes
> -- Creating host directories ... OK
> -- Finding server IP ... 
>    Using 172.19.72.172 as the server IP
> -- Starting OpenShift container ... 
>    Creating initial OpenShift configuration
>    Starting OpenShift using container 'origin'
>    Waiting for API server to start listening
>    OpenShift server started
> -- Adding default OAuthClient redirect URIs ... OK
> -- Installing registry ... OK
> -- Installing router ... OK
> -- Importing image streams ... OK
> -- Importing templates ... OK
> -- Login to server ... OK
> -- Creating initial project "myproject" ... OK
> -- Removing temporary directory ... OK
> -- Server Information ... 
>    OpenShift server started.
>    The server is accessible via web console at:
>        https://172.19.72.172:8443
> 
>    You are logged in as:
>        User:     developer
>        Password: developer
> 
>    To login as administrator:
>        oc login -u system:admin
> 
> Login successful.
> 
> You have one project on this server: "myproject"
> 
> Using project "myproject".
> Now using project "monitoring" on server "https://localhost:8443".
> 
> You can add applications to this project with the 'new-app' command. For example, try:
> 
>     oc new-app centos/ruby-22-centos7~https://github.com/openshift/ruby-ex.git
> 
> to build a new example application in Ruby.
> secret/monitoring-secrets
> template "ops-cent7-zabbix-monitoring" created
> deploymentconfig "mysql" created
> deploymentconfig "oso-cent7-zabbix-server" created
> deploymentconfig "oso-cent7-zabbix-web" created
> deploymentconfig "oso-cent7-zagg-web" created
> route "zabbix-web-ssl-route" created
> route "zagg-web-ssl-route" created
> service "mysql" created
> service "oso-cent7-zabbix-server" created
> service "oso-cent7-zabbix-web" created
> service "oso-cent7-zagg-web" created
> Deploying mysql pod
> Flag --latest has been deprecated, use 'oc rollout latest' instead
> error: cannot trigger a deployment for "mysql" because it contains unresolved images - try 'oc rollout latest dc/mysql'

Any ideas?

**Comment by joelddiaz** [comment]
Use the oc binary version 1.3.3 (https://github.com/openshift/origin/releases/tag/v1.3.3). There are some issues being resolved with oc versions >= 1.4.

**Comment by cragr** [comment]
That worked, thank you.
