### ISSUE TITLE
Issue Deploying Local Development Monitoring

### ISSUE THREAD

**Issue by cragr** [openshift/openshift-tools#2425]
While following the [How to do local development of openshift-tools monitoring components](https://github.com/openshift/openshift-tools/blob/stg/docs/local_development_monitoring.adoc) page, I ran into an issue.

OS: Fedora 25
OC Version: 1.3.3 (initally was running 1.3.4 but ran into an [issue](https://github.com/openshift/openshift-tools/issues/2398))

Ansible and docker are installed and working according to the guide.  After cloning the openshift-tools repo, I ran the [./openshift-tools/docker/build-local-setup-centos7.sh](https://github.com/openshift/openshift-tools/blob/stg/docker/build-local-setup-centos7.sh) script successfully.  My next step was to run the [./openshift-tools/docker/local_development/start-local-dev-env.sh](https://github.com/openshift/openshift-tools/blob/stg/docker/local_development/start-local-dev-env.sh) script which fails with the following error:

> TASK [os_zabbix : Template Create Template] ************************************
> fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: {{ g_template_app_zabbix_server }}: {u'zitems': [{u'zabbix_type': u'internal', u'description': u'A simple count of the number of partition creates output by the housekeeper script.', u'applications': [u'Zabbix server'], u'value_type': u'int', u'key': u'housekeeper_creates', u'units': u''}, {u'zabbix_type': u'internal', u'description': u'A simple count of the number of partition drops output by the housekeeper script.', u'applications': [u'Zabbix server'], u'value_type': u'int', u'key': u'housekeeper_drops', u'units': u''}, {u'zabbix_type': u'internal', u'description': u'A simple count of the number of errors output by the housekeeper script.', u'applications': [u'Zabbix server'], u'value_type': u'int', u'key': u'housekeeper_errors', u'units': u''}, {u'zabbix_type': u'internal', u'description': u'A simple count of the total number of lines output by the housekeeper script.', u'applications': [u'Zabbix server'], u'value_type': u'int', u'key': u'housekeeper_total', u'units': u''}, {u'zabbix_type': u'internal', u'description': u'', u'applications': [u'Zabbix server'], u'value_type': u'float', u'key': u'zabbix[process,alerter,avg,busy]', u'units': u'%'}, {u'zabbix_type': u'internal', u'description': u'', u'applications': [u'Zabbix server'], u'value_type': u'float', u'key': u'zabbix[process,configuration syncer,avg,busy]', u'units': u'%'}, {u'zabbix_type': u'internal', u'description': u'', u'applications': [u'Zabbix server'], u'value_type': u'float', u'key': u'zabbix[process,db watchdog,avg,busy]', u'units': u'%'}, {u'zabbix_type': u'internal', u'description': u'', u'applications': [u'Zabbix server'], u'value_type': u'float', u'key': u'zabbix[process,discoverer,avg,busy]', u'units': u'%'}, {u'zabbix_type': u'internal', u'description': u'', u'applications': [u'Zabbix server'], u'value_type': u'float', u'key': u'zabbix[process,escalator,avg,busy]', u'units': u'%'}, {u'zabbix_type': u'internal', u'description': u'', u'applications': [u'Zabbix server'], u'value_type': u'float', u'key': u'zabbix[process,history syncer,avg,busy]', u'units': u'%'}, {u'zabbix_type': u'internal', u'description': u'', u'applications': [u'Zabbix server'], u'value_type': u'float', u'key': u'zabbix[process,housekeeper,avg,busy]', u'units': u'%'}, {u'zabbix_type': u'internal', u'description': u'', u'applications': [u'Zabbix server'], u'value_type': u'float', u'key': u'zabbix[process,http poller,avg,busy]', u'units': u'%'}, {u'zabbix_type': u'internal', u'description': u'', u'applications': [u'Zabbix server'], u'value_type': u'float', u'key': u'zabbix[process,icmp pinger,avg,busy]', u'units': u'%'}, {u'zabbix_type': u'internal', u'description': u'', u'applications': [u'Zabbix server'], u'value_type': u'float', u'key': u'zabbix[process,ipmi poller,avg,busy]', u'units': u'%'}, {u'zabbix_type': u'internal', u'description': u'', u'applications': [u'Zabbix server'], u'value_type': u'float', u'key': u'zabbix[process,java poller,avg,busy]', u'units': u'%'}, {u'zabbix_type': u'internal', u'description': u'', u'applications': [u'Zabbix server'], u'value_type': u'float', u'key': u'zabbix[process,node watcher,avg,busy]', u'units': u'%'}, {u'zabbix_type': u'internal', u'description': u'', u'applications': [u'Zabbix server'], u'value_type': u'float', u'key': u'zabbix[process,poller,avg,busy]', u'units': u'%'}, {u'zabbix_type': u'internal', u'description': u'', u'applications': [u'Zabbix server'], u'value_type': u'float', u'key': u'zabbix[process,proxy poller,avg,busy]', u'units': u'%'}, {u'zabbix_type': u'internal', u'description': u'', u'applications': [u'Zabbix server'], u'value_type': u'float', u'key': u'zabbix[process,self-monitoring,avg,busy]', u'units': u'%'}, {u'zabbix_type': u'internal', u'description': u'', u'applications': [u'Zabbix server'], u'value_type': u'float', u'key': u'zabbix[process,snmp trapper,avg,busy]', u'units': u'%'}, {u'zabbix_type': u'internal', u'description': u'', u'applications': [u'Zabbix server'], u'value_type': u'float', u'key': u'zabbix[process,timer,avg,busy]', u'units': u'%'}, {u'zabbix_type': u'internal', u'description': u'', u'applications': [u'Zabbix server'], u'value_type': u'float', u'key': u'zabbix[process,trapper,avg,busy]', u'units': u'%'}, {u'zabbix_type': u'internal', u'description': u'', u'applications': [u'Zabbix server'], u'value_type': u'float', u'key': u'zabbix[process,unreachable poller,avg,busy]', u'units': u'%'}, {u'zabbix_type': u'internal', u'description': u'', u'interval': 600, u'applications': [u'Zabbix server'], u'value_type': u'int', u'key': u'zabbix[queue,10m]', u'units': u''}, {u'zabbix_type': u'internal', u'description': u'', u'interval': 600, u'applications': [u'Zabbix server'], u'value_type': u'int', u'key': u'zabbix[queue]', u'units': u''}, {u'zabbix_type': u'internal', u'description': u'', u'applications': [u'Zabbix server'], u'value_type': u'float', u'key': u'zabbix[rcache,buffer,pfree]', u'units': u''}, {u'zabbix_type': u'internal', u'description': u'', u'applications': [u'Zabbix server'], u'value_type': u'float', u'key': u'zabbix[wcache,history,pfree]', u'units': u''}, {u'zabbix_type': u'internal', u'description': u'', u'applications': [u'Zabbix server'], u'value_type': u'float', u'key': u'zabbix[wcache,text,pfree]', u'units': u''}, {u'zabbix_type': u'internal', u'description': u'', u'applications': [u'Zabbix server'], u'value_type': u'float', u'key': u'zabbix[wcache,trend,pfree]', u'units': u''}, {u'zabbix_type': u'internal', u'description': u'', u'applications': [u'Zabbix server'], u'value_type': u'float', u'key': u'zabbix[wcache,values]', u'delta': 1, u'units': u''}, {u'zabbix_type': u'trapper', u'applications': [u'Zabbix server'], u'value_type': u'int', u'description': u'How many versions behind is the current running version of Zabbix', u'key': u'zabbix.software.version.disparity'}], u'ztriggers': [{u'priority': u'high', u'url': u'https://github.com/openshift/ops-sop/blob/master/Services/Zabbix/Custom_Checks.asciidoc', u'expression': u'{Template App Zabbix Server:web.test.fail[check_v2_zabbix_web].last(#1)}<>0 and {Template App Zabbix Server:web.test.fail[check_v2_zabbix_web].last(#2)}<>0', u'description': u'Zabbix v2 Web UI is not responding', u'name': u'Zabbix v2 Web UI is not responding'}, {u'priority': u'avg', u'url': u'https://github.com/openshift/ops-sop/blob/master/Alerts/Zabbix_DB_Housekeeping.asciidoc', u'expression': u'{Template App Zabbix Server:housekeeper_errors.last(0)}+{Template App Zabbix Server:housekeeper_creates.last(0)}+{Template App Zabbix Server:housekeeper_drops.last(0)}<>{Template App Zabbix Server:housekeeper_total.last(0)}', u'description': u\"There has been unexpected output while running the housekeeping script on the Zabbix. There are only three kinds of lines we expect to see in the output, and we've gotten something enw.\\r\\n\\r\\nCheck the script's output in /var/lib/zabbix/state for more details.\", u'name': u'Unexpected output in Zabbix DB Housekeeping'}, {u'priority': u'high', u'url': u'https://github.com/openshift/ops-sop/blob/master/Alerts/Zabbix_state_check.asciidoc', u'expression': u'{Template App Zabbix Server:housekeeper_errors.last(0)}>0', u'description': u\"An error has occurred during running the housekeeping script on the Zabbix. Check the script's output in /var/lib/zabbix/state for more details.\", u'name': u'Errors during Zabbix DB Housekeeping'}, {u'priority': u'avg', u'url': u'https://github.com/openshift/ops-sop/blob/master/Alerts/Zabbix_state_check.asciidoc', u'expression': u'{Template App Zabbix Server:zabbix[process,alerter,avg,busy].min(600)}>75', u'description': u'', u'name': u'Zabbix alerter processes more than 75% busy'}, {u'priority': u'avg', u'url': u'https://github.com/openshift/ops-sop/blob/master/Alerts/Zabbix_state_check.asciidoc', u'expression': u'{Template App Zabbix Server:zabbix[process,configuration syncer,avg,busy].min(600)}>75', u'description': u'', u'name': u'Zabbix configuration syncer processes more than 75% busy'}, {u'priority': u'avg', u'url': u'https://github.com/openshift/ops-sop/blob/master/Alerts/Zabbix_state_check.asciidoc', u'expression': u'{Template App Zabbix Server:zabbix[process,db watchdog,avg,busy].min(600)}>75', u'description': u'', u'name': u'Zabbix db watchdog processes more than 75% busy'}, {u'priority': u'avg', u'url': u'https://github.com/openshift/ops-sop/blob/master/Alerts/Zabbix_state_check.asciidoc', u'expression': u'{Template App Zabbix Server:zabbix[process,discoverer,avg,busy].min(600)}>75', u'description': u'', u'name': u'Zabbix discoverer processes more than 75% busy'}, {u'priority': u'avg', u'url': u'https://github.com/openshift/ops-sop/blob/master/Alerts/Zabbix_state_check.asciidoc', u'expression': u'{Template App Zabbix Server:zabbix[process,escalator,avg,busy].min(600)}>75', u'description': u'', u'name': u'Zabbix escalator processes more than 75% busy'}, {u'priority': u'avg', u'url': u'https://github.com/openshift/ops-sop/blob/master/Alerts/Zabbix_state_check.asciidoc', u'expression': u'{Template App Zabbix Server:zabbix[process,history syncer,avg,busy].min(600)}>75', u'description': u'', u'name': u'Zabbix history syncer processes more than 75% busy'}, {u'priority': u'avg', u'url': u'https://github.com/openshift/ops-sop/blob/master/Alerts/Zabbix_state_check.asciidoc', u'expression': u'{Template App Zabbix Server:zabbix[process,housekeeper,avg,busy].min(1800)}>75', u'description': u'', u'name': u'Zabbix housekeeper processes more than 75% busy'}, {u'priority': u'avg', u'url': u'https://github.com/openshift/ops-sop/blob/master/Alerts/Zabbix_state_check.asciidoc', u'expression': u'{Template App Zabbix Server:zabbix[process,http poller,avg,busy].min(600)}>75', u'description': u'', u'name': u'Zabbix http poller processes more than 75% busy'}, {u'priority': u'avg', u'url': u'https://github.com/openshift/ops-sop/blob/master/Alerts/Zabbix_state_check.asciidoc', u'expression': u'{Template App Zabbix Server:zabbix[process,icmp pinger,avg,busy].min(600)}>75', u'description': u'', u'name': u'Zabbix icmp pinger processes more than 75% busy'}, {u'priority': u'avg', u'url': u'https://github.com/openshift/ops-sop/blob/master/Alerts/Zabbix_state_check.asciidoc', u'expression': u'{Template App Zabbix Server:zabbix[process,ipmi poller,avg,busy].min(600)}>75', u'description': u'', u'name': u'Zabbix ipmi poller processes more than 75% busy'}, {u'priority': u'avg', u'url': u'https://github.com/openshift/ops-sop/blob/master/Alerts/Zabbix_state_check.asciidoc', u'expression': u'{Template App Zabbix Server:zabbix[process,java poller,avg,busy].min(600)}>75', u'description': u'', u'name': u'Zabbix java poller processes more than 75% busy'}, {u'priority': u'avg', u'url': u'https://github.com/openshift/ops-sop/blob/master/Alerts/Zabbix_state_check.asciidoc', u'expression': u'{Template App Zabbix Server:zabbix[process,node watcher,avg,busy].min(600)}>75', u'description': u'', u'name': u'Zabbix node watcher processes more than 75% busy'}, {u'priority': u'high', u'url': u'https://github.com/openshift/ops-sop/blob/master/Alerts/Zabbix_state_check.asciidoc', u'expression': u'{Template App Zabbix Server:zabbix[process,poller,avg,busy].min(600)}>75', u'description': u'', u'name': u'Zabbix poller processes more than 75% busy'}, {u'priority': u'avg', u'url': u'https://github.com/openshift/ops-sop/blob/master/Alerts/Zabbix_state_check.asciidoc', u'expression': u'{Template App Zabbix Server:zabbix[process,proxy poller,avg,busy].min(600)}>75', u'description': u'', u'name': u'Zabbix proxy poller processes more than 75% busy'}, {u'priority': u'avg', u'url': u'https://github.com/openshift/ops-sop/blob/master/Alerts/Zabbix_state_check.asciidoc', u'expression': u'{Template App Zabbix Server:zabbix[process,self-monitoring,avg,busy].min(600)}>75', u'description': u'', u'name': u'Zabbix self-monitoring processes more than 75% busy'}, {u'priority': u'avg', u'url': u'https://github.com/openshift/ops-sop/blob/master/Alerts/Zabbix_state_check.asciidoc', u'expression': u'{Template App Zabbix Server:zabbix[process,snmp trapper,avg,busy].min(600)}>75', u'description': u'', u'name': u'Zabbix snmp trapper processes more than 75% busy'}, {u'priority': u'avg', u'url': u'https://github.com/openshift/ops-sop/blob/master/Alerts/Zabbix_state_check.asciidoc', u'expression': u'{Template App Zabbix Server:zabbix[process,timer,avg,busy].min(600)}>75', u'description': u'Timer processes usually are busy because they have to process time based trigger functions', u'name': u'Zabbix timer processes more than 75% busy'}, {u'priority': u'avg', u'url': u'https://github.com/openshift/ops-sop/blob/master/Alerts/Zabbix_state_check.asciidoc', u'expression': u'{Template App Zabbix Server:zabbix[process,trapper,avg,busy].min(600)}>75', u'description': u'', u'name': u'Zabbix trapper processes more than 75% busy'}, {u'priority': u'avg', u'url': u'https://github.com/openshift/ops-sop/blob/master/Alerts/Zabbix_state_check.asciidoc', u'expression': u'{Template App Zabbix Server:zabbix[process,unreachable poller,avg,busy].min(600)}>75', u'description': u'', u'name': u'Zabbix unreachable poller processes more than 75% busy'}, {u'priority': u'high', u'url': u'https://github.com/openshift/ops-sop/blob/master/Alerts/data_lost_overview_plugin.asciidoc', u'expression': u'{Template App Zabbix Server:zabbix[queue,10m].min(600)}>1000', u'description': u'This alert generally indicates a performance problem or a problem with the zabbix-server or proxy.\\r\\n\\r\\nThe first place to check for issues is Administration > Queue. Be sure to check the general view and the per-proxy view.', u'name': u'More than 1000 items having missing data for more than 10 minutes'}, {u'priority': u'info', u'url': u'https://github.com/openshift/ops-sop/blob/master/Alerts/check_cache.asciidoc', u'expression': u'{Template App Zabbix Server:zabbix[rcache,buffer,pfree].min(600)}<5', u'description': u'Consider increasing CacheSize in the zabbix_server.conf configuration file', u'name': u'Less than 5% free in the configuration cache'}, {u'priority': u'avg', u'url': u'https://github.com/openshift/ops-sop/blob/master/Alerts/check_cache.asciidoc', u'expression': u'{Template App Zabbix Server:zabbix[wcache,history,pfree].min(600)}<25', u'description': u'', u'name': u'Less than 25% free in the history cache'}, {u'priority': u'avg', u'url': u'https://github.com/openshift/ops-sop/blob/master/Alerts/check_cache.asciidoc', u'expression': u'{Template App Zabbix Server:zabbix[wcache,text,pfree].min(600)}<25', u'description': u'', u'name': u'Less than 25% free in the text history cache'}, {u'priority': u'avg', u'url': u'https://github.com/openshift/ops-sop/blob/master/Alerts/check_cache.asciidoc', u'expression': u'{Template App Zabbix Server:zabbix[wcache,trend,pfree].min(600)}<25', u'description': u'', u'name': u'Less than 25% free in the trends cache'}, {u'priority': u'info', u'url': u'https://github.com/openshift/ops-sop/blob/master/V3/Alerts/check_zabbix_version.asciidoc', u'expression': u'{Template App Zabbix Server:zabbix.software.version.disparity.last(0)}>0', u'name': u'New version of Zabbix is available', u'description': u'There is a new version of Zabbix available. This Zabbix server should be updated.'}], u'name': u'Template App Zabbix Server', u'zhttptests': [{u'application': u'Zabbix server', u'interval': 60, u'steps': [{u'url': u'{{ g_v2_monitor_url }}', u'status_codes': u'200', u'required': u'Zabbix', u'name': u'Check v2 Zabbix web', u'no': 1}], u'name': u'check_v2_zabbix_web'}]}: 'g_v2_monitor_url' is undefined\n\nThe error appears to have been in '/home/countpickering/openshift-tools/ansible/roles/lib_zabbix/tasks/create_template.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Template Create Template\n  ^ here\n"}
> 	to retry, use: --limit @/home/countpickering/openshift-tools/ansible/playbooks/adhoc/zabbix_setup/oo-config-zaio.retry
> 
> PLAY RECAP *********************************************************************
> localhost                  : ok=80   changed=48   unreachable=0    failed=1 

At this point, some of the environment is up and working.  The OpenShift Web Console is working along with the deployments and pods: mysql, oso-cent7-zabbix-web, oso-cent7-zabbix-server.  The oso-cent7-zagg-web depoyment says "No deployments".  Also I noticed my hosts file has set the oso-cent7-zabbix-web record, but not the oso-cent7-zagg-web record.

The error message above reads as if the mentioned create_template.yml has a syntax issue, but I was unable to visibly find it.  Any help on this issue is appreciated.

**Comment by joelddiaz** [comment]
You want to try commenting out some bits that assume some variable are defined:

    diff --git a/ansible/roles/os_zabbix/vars/template_app_zabbix_server.yml b/ansible/roles/os_zabbix/vars/template_app_zabbix_server.yml
    index 394331a..78864b4 100644
    --- a/ansible/roles/os_zabbix/vars/template_app_zabbix_server.yml
    +++ b/ansible/roles/os_zabbix/vars/template_app_zabbix_server.yml
    @@ -253,28 +253,28 @@ g_template_app_zabbix_server:
          value_type: int
          zabbix_type: trapper
     
    -   zhttptests:
    -   - name: check_v2_zabbix_web
    -     interval: 60
    -     application: Zabbix server
    -     steps:
    -     - name: "Check v2 Zabbix web"
    -       url: "{{ g_v2_monitor_url }}"
    -       status_codes: '200'
    -       required: Zabbix
    -       'no': 1
    -     #- name: "Hit some other service"
    -     #  url: "http://google.com"
    -     #  status_codes: '200'
    -     #  required: google
    -     #  'no': 2
    +     #   zhttptests:
    +     #   - name: check_v2_zabbix_web
    +     #     interval: 60
    +     #     application: Zabbix server
    +     #     steps:
    +     #     - name: "Check v2 Zabbix web"
    +     #       url: "{{ g_v2_monitor_url }}"
    +     #       status_codes: '200'
    +     #       required: Zabbix
    +     #       'no': 1
    +     #     #- name: "Hit some other service"
    +     #     #  url: "http://google.com"
    +     #     #  status_codes: '200'
    +     #     #  required: google
    +     #     #  'no': 2
     
        ztriggers:
    -   - description: "Zabbix v2 Web UI is not responding"
    -     expression: "{Template App Zabbix Server:web.test.fail[check_v2_zabbix_web].last(#1)}<>0 and {Template App Zabbix Server:web.test.fail[check_v2_zabbix_web].last(#2)}<>0"
    -     name: "Zabbix v2 Web UI is not responding"
    -     priority: high
    -     url: https://github.com/openshift/ops-sop/blob/master/Services/Zabbix/Custom_Checks.asciidoc
    +           #   - description: "Zabbix v2 Web UI is not responding"
    +           #     expression: "{Template App Zabbix Server:web.test.fail[check_v2_zabbix_web].last(#1)}<>0 and {Template App Zabbix Server:web.test.fail[check_v2_zabbix_web].last(#2)}<>0"
    +           #     name: "Zabbix v2 Web UI is not responding"
    +           #     priority: high
    +           #     url: https://github.com/openshift/ops-sop/blob/master/Services/Zabbix/Custom_Checks.asciidoc
     
        - description: "There has been unexpected output while running the housekeeping script\
            \ on the Zabbix. There are only three kinds of lines we expect to see in the output,\

**Comment by CountPickering** [comment]
How were you able to clean that error message up to human-readable format?

**Comment by cragr** [comment]
You were correct.  The "g_v2_monitor_url" variable at line 263 of /ansible/roles/os_zabbix/vars/template_app_zabbix_server.yml has no value assigned.  I manually assigned it "http://google.com" as the comments suggest.  The build finished successfully and I am monitoring.  Thanks.
