### ISSUE TITLE
Make some of your awesome modules usable by others?

### ISSUE THREAD

**Issue by gregswift** [openshift/openshift-tools#2944]
So I've been using Zabbix for a while and making zabbix modules to manage the resources has been on my todo list for a long time.  Yall did it. Which rocks.  So I'm playing with bringing it out into a [separate repo](https://github.com/gregswift/ansible-lib_zabbix), and would totally love to see it recommended for upstream ansible.  

I'm sure there are probably a few others that would be good to do this with.

Thoughts?

**Comment by ivanhorvath** [comment]
We are trying to get away from Zabbix, so getting priority on this is rather unlikely at ths time. If you already doing the work, but just need eyes on it, someone on the team might be able to help with that. As far as the legal bits go, I would have to ask around what that means under the Apache license.

**Comment by gregswift** [comment]
I'm planning on doing the work but want to make sure everything is above board license wise.

Where are y'all moving to from zabbix?

**Comment by gregswift** [comment]
https://en.m.wikipedia.org/wiki/Apache_License makes it sound like main thing i need to do is ensure changes are stated somewhere

**Comment by gregswift** [comment]
On top of what I'm already doing that is

**Comment by joelddiaz** [comment]
👍 to getting this more easily consumable outside this repo
