### ISSUE TITLE
Building monitoring containers on RHEL7

### ISSUE THREAD

**Issue by StevenBarre** [openshift/openshift-tools#2996]
Hello

In #2887 a change was made to roll back to older RHEL 7.3, but I was still having issues building the containers.

https://github.com/slashterix/openshift-tools/commit/a0e65d6578a511eaa0f9489a95b4368bc5127754 shows all the changes I needed to make to get all the containers to build.

I'm running OCP 3.6 Enterprise on premises (on VMware and physical hosts) and am trying to give this Zabbix monitoring a try since there isn't much built in for monitoring the platform.

I'd appreciate any feedback as I'm new here before I open a PR. Have I made any drastic mistakes or done things that don't work with the flow for others?

**Comment by slashterix** [comment]
https://github.com/slashterix/openshift-tools/commit/17ec0b035aea7cb18fc6e78508791b9a49f2a037
