### ISSUE TITLE
instance of suspicious comments

### ISSUE THREAD

**Issue by rayhanur-rahman** [openshift/openshift-tools#4009]
Greetings,

I am a security researcher, who is looking for security smells in Ansible scripts.
I found instances where certain keywords such as TODO, HACK, FIXME, bug repository IDs, in comments within Chef scripts.
According to the Common Weakness Enumeration organization this is a security weakness
(CWE-546: Suspicious Comment https://cwe.mitre.org/data/definitions/546.html).

I am trying to find out if you agree with the findings. I think it is possible to have a nuanced perspective. Any feedback is appreciated.

Any feedback is appreciated.

source: https://github.com/openshift/openshift-tools/blob/prod/openshift/installer/vendored/openshift-ansible-3.5.127/playbooks/common/openshift-cluster/upgrades/v3_5/validator.yml

**Comment by RiRa12621** [comment]
Since the file that you mentioned does not exist anymore, can you point out what exactly you were looking for and what you found?
